language: cpp
compiler:
  - gcc
  - clang
before_script: git submodule update --init --recursive && mkdir ../build-qmake ../build-cmake && cd ../build-qmake && qmake ../petroules-utilities-qt/petroules-utilities-qt.pro -r && cd ../build-cmake && cmake -DCMAKE_BUILD_TYPE=Release ../petroules-utilities-qt && cd ..
script: make -C build-qmake && make -C build-cmake
branches:
  only:
    - master
notifications:
  recipients:
    - jake.petroules+travis@petroules.com
  email:
    on_success: change
    on_failure: always

