language: cpp
compiler:
  - gcc
  - clang
before_script: ./.travis/configure.sh
script: ./.travis/make.sh
branches:
  only:
    - master
notifications:
  recipients:
    - jake.petroules+travis@petroules.com
  email:
    on_success: change
    on_failure: always
