language: cpp
compiler:
  - gcc
  - clang
before_script: ./configure.sh
script: ./make.sh
branches:
  only:
    - master
notifications:
  recipients:
    - jake.petroules+travis@petroules.com
  email:
    on_success: change
    on_failure: always
