#ifndef PETROULESUTILITIES_GLOBAL_H
#define PETROULESUTILITIES_GLOBAL_H

#include <QtGui>

#if defined(PETROULESUTILITIES_EXPORTS)
#  define PETROULESUTILITIESSHARED_EXPORT Q_DECL_EXPORT
#  define QT_QTSINGLECOREAPPLICATION_EXPORT Q_DECL_EXPORT
#  define QT_QTSINGLEAPPLICATION_EXPORT
#elif defined(PETROULESUTILITIES_IMPORTS)
#  define PETROULESUTILITIESSHARED_EXPORT Q_DECL_IMPORT
#  define QT_QTSINGLEAPPLICATION_IMPORT
#else
#  define PETROULESUTILITIESSHARED_EXPORT
#endif

#endif // PETROULESUTILITIES_GLOBAL_H
