#ifndef PETROULESUTILITIES_GLOBAL_H
#define PETROULESUTILITIES_GLOBAL_H

#include <QtGui>

#if defined(PETROULESUTILITIES_LIBRARY)
#  define PETROULESUTILITIESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PETROULESUTILITIESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PETROULESUTILITIES_GLOBAL_H
